[Application Options]
restlisten=0.0.0.0:8080
rpclisten=0.0.0.0:10009
listen=0.0.0.0:9735
maxpendingchannels=10
alias=parsebit
color=#F7931A
no-macaroons=false

[Bitcoin]
bitcoin.active=1
bitcoin.mainnet=1
bitcoin.node=neutrino

[Neutrino]
neutrino.connect=btcd-mainnet.lightning.computer:10009
neutrino.connect=neutrino.bitlum.io
neutrino.connect=neutrino.olaoluwa.dev

[tor]
tor.active=0
